language: rust

env:
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - cargo test
  - cargo build