language: rust
sudo: false
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
rust:
  - nightly
  - stable

addons:
  apt:
    packages:
      - libgtk-3-dev

script:
  - rustc --version
  - cargo test --no-default-features
  - cargo build --no-default-features
