language: rust
# sudo: false
env: 
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
rust:
  - nightly
  - stable
before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update
install:
  - sudo apt-get install gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - cargo test --no-default-features
  - cargo build --no-default-features
