language: rust
sudo: false
rust:
- nightly
- stable
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - apt-get update
install:
  - apt-get install gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - cargo test
  - cargo build
