[package]
name = "rrun"
version = "0.0.5"
authors = ["me@bstr.eu"]
repository = "https://github.com/buster/rrun"
keywords = ["gtk", "tool", "bash"]
license = "GPL-3.0+"
description = "minimalistic command launcher in rust similar to gmrun"

[dependencies.rgtk]
git = "git://github.com/jeremyletang/rgtk.git"
features = ["GTK_3_10"]

[dependencies]
log = "*"
env_logger = "*"

[[bin]]
name = "rrun"
