[package]
name = "rrun"
version = "0.0.6"
authors = ["me@bstr.eu"]
repository = "https://github.com/buster/rrun"
keywords = ["gtk", "tool", "bash"]
license = "GPL-3.0+"
description = "minimalistic command launcher in rust similar to gmrun"

[dependencies.gtk]
git = "https://github.com/rust-gnome/gtk"

[dependencies.gdk]
git = "https://github.com/rust-gnome/gdk"
default-features = false

[dependencies]
log = "*"
env_logger = "*"

[features]
default = ["search_entry"]
search_entry = ["gtk/gtk_3_10"]

[[bin]]
name = "rrun"
