[[completion]]
type="ruby_code"
trigger="rb (.*)"

[[completion]]
type="command"
command="echo {}"

[[completion]]
type="command"
command="compgen -A command {}"

[[runner]]
type="command"
command="bash -i -c '(history -s {}; history -a) && {}'"

[[runner]]
type="ruby_code"
command="ruby -e 'puts {}'"
