[[completion]]
type="ruby_code"
trigger="rb (.*)"

[[completion]]
type="numeric_expression"
trigger="([0-9]+.*)"

[[completion]]
type="url"
trigger="g (.*)"
command="ruby -r uri -e '@q = \"{}\"; @q_quoted = URI.escape(@q); puts \"Google for #@q\thttps://www.google.com/search?q=#@q_quoted\"'"

# [[completion]]
# type="command"
# command="echo {}"

[[completion]]
type="command"
command="compgen -A command {} | sort | uniq"

[[runner]]
type="command"
command="bash -i -c '(history -s {}; history -a) && {}'"

[[runner]]
type="ruby_code"
command="ruby -e 'puts {}'"

[[runner]]
type="numeric_expression"
command="ruby -e 'puts {}'"

[[runner]]
type="url"
command="google-chrome --new-window {}"
